-- Generated from src/features/draft-room/players.ts — do not edit by hand.
-- Regenerate: node scripts/generate-seed.mjs
-- Idempotent: wipes the players table (and any picks referencing it) first, so
-- it is safe to re-run after the player pool changes.

truncate table players cascade;

insert into players (name, role, rating, metadata) values
  ('Lionel Messi', 'FWD', 99, '{"club":"Barcelona","nationality":"Argentina","era":"2000s–20s","categories":["GOAT_XI"]}'::jsonb),
  ('Pelé', 'FWD', 99, '{"club":"Santos","nationality":"Brazil","era":"1950s–60s","categories":["GOAT_XI"]}'::jsonb),
  ('Cristiano Ronaldo', 'FWD', 98, '{"club":"Real Madrid","nationality":"Portugal","era":"2000s–20s","categories":["GOAT_XI"]}'::jsonb),
  ('Diego Maradona', 'FWD', 98, '{"club":"Napoli","nationality":"Argentina","era":"1980s–90s","categories":["GOAT_XI"]}'::jsonb),
  ('Alfredo Di Stéfano', 'FWD', 97, '{"club":"Real Madrid","nationality":"Argentina","era":"1950s–60s","categories":["GOAT_XI"]}'::jsonb),
  ('Johan Cruyff', 'FWD', 97, '{"club":"Ajax","nationality":"Netherlands","era":"1970s","categories":["GOAT_XI"]}'::jsonb),
  ('Ferenc Puskás', 'FWD', 96, '{"club":"Real Madrid","nationality":"Hungary","era":"1950s–60s","categories":["GOAT_XI"]}'::jsonb),
  ('Franz Beckenbauer', 'DEF', 96, '{"club":"Bayern Munich","nationality":"Germany","era":"1970s","categories":["GOAT_XI"]}'::jsonb),
  ('Ronaldo Nazário', 'FWD', 96, '{"club":"Real Madrid","nationality":"Brazil","era":"1990s–2000s","categories":["GOAT_XI"]}'::jsonb),
  ('Zinedine Zidane', 'MID', 96, '{"club":"Real Madrid","nationality":"France","era":"1990s–2000s","categories":["GOAT_XI"]}'::jsonb),
  ('Eusébio', 'FWD', 95, '{"club":"Benfica","nationality":"Portugal","era":"1960s–70s","categories":["GOAT_XI"]}'::jsonb),
  ('Garrincha', 'FWD', 95, '{"club":"Botafogo","nationality":"Brazil","era":"1950s–60s","categories":["GOAT_XI"]}'::jsonb),
  ('George Best', 'FWD', 95, '{"club":"Manchester United","nationality":"Northern Ireland","era":"1960s–70s","categories":["GOAT_XI"]}'::jsonb),
  ('Marco van Basten', 'FWD', 95, '{"club":"AC Milan","nationality":"Netherlands","era":"1980s–90s","categories":["GOAT_XI"]}'::jsonb),
  ('Michel Platini', 'MID', 95, '{"club":"Juventus","nationality":"France","era":"1980s","categories":["GOAT_XI"]}'::jsonb),
  ('Paolo Maldini', 'DEF', 95, '{"club":"AC Milan","nationality":"Italy","era":"1990s–2000s","categories":["GOAT_XI"]}'::jsonb),
  ('Ronaldinho', 'FWD', 95, '{"club":"Barcelona","nationality":"Brazil","era":"2000s","categories":["GOAT_XI"]}'::jsonb),
  ('Andrés Iniesta', 'MID', 94, '{"club":"Barcelona","nationality":"Spain","era":"2000s–10s","categories":["GOAT_XI"]}'::jsonb),
  ('Bobby Charlton', 'MID', 94, '{"club":"Manchester United","nationality":"England","era":"1960s–70s","categories":["GOAT_XI"]}'::jsonb),
  ('Franco Baresi', 'DEF', 94, '{"club":"AC Milan","nationality":"Italy","era":"1980s–90s","categories":["GOAT_XI"]}'::jsonb),
  ('Gerd Müller', 'FWD', 94, '{"club":"Bayern Munich","nationality":"Germany","era":"1970s","categories":["GOAT_XI"]}'::jsonb),
  ('Lev Yashin', 'GK', 94, '{"club":"Dynamo Moscow","nationality":"USSR","era":"1950s–60s","categories":["GOAT_XI"]}'::jsonb),
  ('Xavi', 'MID', 94, '{"club":"Barcelona","nationality":"Spain","era":"2000s–10s","categories":["GOAT_XI"]}'::jsonb),
  ('Cafu', 'DEF', 93, '{"club":"AC Milan","nationality":"Brazil","era":"1990s–2000s","categories":["GOAT_XI"]}'::jsonb),
  ('Gianluigi Buffon', 'GK', 93, '{"club":"Juventus","nationality":"Italy","era":"2000s–10s","categories":["GOAT_XI"]}'::jsonb),
  ('Lothar Matthäus', 'MID', 93, '{"club":"Bayern Munich","nationality":"Germany","era":"1980s–90s","categories":["GOAT_XI"]}'::jsonb),
  ('Luka Modrić', 'MID', 93, '{"club":"Real Madrid","nationality":"Croatia","era":"2010s–20s","categories":["GOAT_XI"]}'::jsonb),
  ('Roberto Baggio', 'FWD', 93, '{"club":"Juventus","nationality":"Italy","era":"1990s","categories":["GOAT_XI"]}'::jsonb),
  ('Roberto Carlos', 'DEF', 93, '{"club":"Real Madrid","nationality":"Brazil","era":"1990s–2000s","categories":["GOAT_XI"]}'::jsonb),
  ('Romário', 'FWD', 93, '{"club":"Barcelona","nationality":"Brazil","era":"1990s","categories":["GOAT_XI"]}'::jsonb),
  ('Thierry Henry', 'FWD', 93, '{"club":"Arsenal","nationality":"France","era":"2000s","categories":["GOAT_XI"]}'::jsonb),
  ('Zico', 'MID', 93, '{"club":"Flamengo","nationality":"Brazil","era":"1980s","categories":["GOAT_XI"]}'::jsonb),
  ('Andrea Pirlo', 'MID', 92, '{"club":"AC Milan","nationality":"Italy","era":"2000s–10s","categories":["GOAT_XI"]}'::jsonb),
  ('Bobby Moore', 'DEF', 92, '{"club":"West Ham United","nationality":"England","era":"1960s–70s","categories":["GOAT_XI"]}'::jsonb),
  ('Carlos Alberto', 'DEF', 92, '{"club":"Santos","nationality":"Brazil","era":"1970s","categories":["GOAT_XI"]}'::jsonb),
  ('Dino Zoff', 'GK', 92, '{"club":"Juventus","nationality":"Italy","era":"1970s–80s","categories":["GOAT_XI"]}'::jsonb),
  ('Gordon Banks', 'GK', 92, '{"club":"Stoke City","nationality":"England","era":"1960s–70s","categories":["GOAT_XI"]}'::jsonb),
  ('Iker Casillas', 'GK', 92, '{"club":"Real Madrid","nationality":"Spain","era":"2000s–10s","categories":["GOAT_XI"]}'::jsonb),
  ('Kaká', 'MID', 92, '{"club":"AC Milan","nationality":"Brazil","era":"2000s","categories":["GOAT_XI"]}'::jsonb),
  ('Kenny Dalglish', 'FWD', 92, '{"club":"Liverpool","nationality":"Scotland","era":"1970s–80s","categories":["GOAT_XI"]}'::jsonb),
  ('Kylian Mbappé', 'FWD', 92, '{"club":"Paris Saint-Germain","nationality":"France","era":"2010s–20s","categories":["GOAT_XI"]}'::jsonb),
  ('Manuel Neuer', 'GK', 92, '{"club":"Bayern Munich","nationality":"Germany","era":"2010s–20s","categories":["GOAT_XI"]}'::jsonb),
  ('Ruud Gullit', 'MID', 92, '{"club":"AC Milan","nationality":"Netherlands","era":"1980s–90s","categories":["GOAT_XI"]}'::jsonb),
  ('Sergio Ramos', 'DEF', 92, '{"club":"Real Madrid","nationality":"Spain","era":"2000s–10s","categories":["GOAT_XI"]}'::jsonb),
  ('Sócrates', 'MID', 92, '{"club":"Corinthians","nationality":"Brazil","era":"1980s","categories":["GOAT_XI"]}'::jsonb),
  ('Carles Puyol', 'DEF', 91, '{"club":"Barcelona","nationality":"Spain","era":"2000s–10s","categories":["GOAT_XI"]}'::jsonb),
  ('Daniel Passarella', 'DEF', 91, '{"club":"River Plate","nationality":"Argentina","era":"1970s–80s","categories":["GOAT_XI"]}'::jsonb),
  ('Didier Drogba', 'FWD', 91, '{"club":"Chelsea","nationality":"Ivory Coast","era":"2000s–10s","categories":["GOAT_XI"]}'::jsonb),
  ('Fabio Cannavaro', 'DEF', 91, '{"club":"Real Madrid","nationality":"Italy","era":"2000s","categories":["GOAT_XI"]}'::jsonb),
  ('Frank Rijkaard', 'MID', 91, '{"club":"AC Milan","nationality":"Netherlands","era":"1980s–90s","categories":["GOAT_XI"]}'::jsonb),
  ('Giacinto Facchetti', 'DEF', 91, '{"club":"Inter Milan","nationality":"Italy","era":"1960s–70s","categories":["GOAT_XI"]}'::jsonb),
  ('Kevin De Bruyne', 'MID', 91, '{"club":"Manchester City","nationality":"Belgium","era":"2010s–20s","categories":[]}'::jsonb),
  ('Neymar', 'FWD', 91, '{"club":"Barcelona","nationality":"Brazil","era":"2010s–20s","categories":["GOAT_XI"]}'::jsonb),
  ('Oliver Kahn', 'GK', 91, '{"club":"Bayern Munich","nationality":"Germany","era":"1990s–2000s","categories":["GOAT_XI"]}'::jsonb),
  ('Paul Scholes', 'MID', 91, '{"club":"Manchester United","nationality":"England","era":"1990s–2000s","categories":["GOAT_XI"]}'::jsonb),
  ('Peter Schmeichel', 'GK', 91, '{"club":"Manchester United","nationality":"Denmark","era":"1990s","categories":["GOAT_XI"]}'::jsonb),
  ('Philipp Lahm', 'DEF', 91, '{"club":"Bayern Munich","nationality":"Germany","era":"2000s–10s","categories":["GOAT_XI"]}'::jsonb),
  ('Raymond Kopa', 'FWD', 91, '{"club":"Real Madrid","nationality":"France","era":"1950s–60s","categories":["GOAT_XI"]}'::jsonb),
  ('Rivaldo', 'MID', 91, '{"club":"Barcelona","nationality":"Brazil","era":"1990s–2000s","categories":["GOAT_XI"]}'::jsonb),
  ('Robert Lewandowski', 'FWD', 91, '{"club":"Bayern Munich","nationality":"Poland","era":"2010s–20s","categories":[]}'::jsonb),
  ('Steven Gerrard', 'MID', 91, '{"club":"Liverpool","nationality":"England","era":"2000s–10s","categories":["GOAT_XI"]}'::jsonb),
  ('Virgil van Dijk', 'DEF', 91, '{"club":"Liverpool","nationality":"Netherlands","era":"2010s–20s","categories":["GOAT_XI"]}'::jsonb),
  ('Karim Benzema', 'FWD', 90, '{"club":"Real Madrid","nationality":"France","era":"2010s–20s","categories":[]}'::jsonb),
  ('Luis Suárez', 'FWD', 90, '{"club":"Barcelona","nationality":"Uruguay","era":"2010s","categories":[]}'::jsonb),
  ('Sergio Agüero', 'FWD', 90, '{"club":"Manchester City","nationality":"Argentina","era":"2010s","categories":[]}'::jsonb),
  ('Zlatan Ibrahimović', 'FWD', 90, '{"club":"AC Milan","nationality":"Sweden","era":"2000s–10s","categories":[]}'::jsonb),
  ('Alessandro Nesta', 'DEF', 89, '{"club":"AC Milan","nationality":"Italy","era":"2000s","categories":[]}'::jsonb),
  ('Andriy Shevchenko', 'FWD', 89, '{"club":"AC Milan","nationality":"Ukraine","era":"2000s","categories":[]}'::jsonb),
  ('Gabriel Batistuta', 'FWD', 89, '{"club":"Fiorentina","nationality":"Argentina","era":"1990s","categories":[]}'::jsonb),
  ('George Weah', 'FWD', 89, '{"club":"AC Milan","nationality":"Liberia","era":"1990s","categories":[]}'::jsonb),
  ('Raúl', 'FWD', 89, '{"club":"Real Madrid","nationality":"Spain","era":"1990s–2000s","categories":[]}'::jsonb),
  ('Samuel Eto''o', 'FWD', 89, '{"club":"Barcelona","nationality":"Cameroon","era":"2000s–10s","categories":[]}'::jsonb),
  ('Alan Shearer', 'FWD', 88, '{"club":"Newcastle United","nationality":"England","era":"1990s–2000s","categories":[]}'::jsonb),
  ('David Villa', 'FWD', 88, '{"club":"Valencia","nationality":"Spain","era":"2000s–10s","categories":[]}'::jsonb),
  ('Frank Lampard', 'MID', 88, '{"club":"Chelsea","nationality":"England","era":"2000s","categories":[]}'::jsonb),
  ('Gerard Piqué', 'DEF', 88, '{"club":"Barcelona","nationality":"Spain","era":"2010s","categories":[]}'::jsonb),
  ('Hugo Sánchez', 'FWD', 88, '{"club":"Real Madrid","nationality":"Mexico","era":"1980s–90s","categories":[]}'::jsonb),
  ('Juan Román Riquelme', 'MID', 88, '{"club":"Boca Juniors","nationality":"Argentina","era":"2000s","categories":[]}'::jsonb),
  ('Patrick Vieira', 'MID', 88, '{"club":"Arsenal","nationality":"France","era":"1990s–2000s","categories":[]}'::jsonb),
  ('Rio Ferdinand', 'DEF', 88, '{"club":"Manchester United","nationality":"England","era":"2000s","categories":[]}'::jsonb),
  ('Roy Keane', 'MID', 88, '{"club":"Manchester United","nationality":"Ireland","era":"1990s–2000s","categories":[]}'::jsonb),
  ('Clarence Seedorf', 'MID', 87, '{"club":"AC Milan","nationality":"Netherlands","era":"2000s","categories":[]}'::jsonb),
  ('Edwin van der Sar', 'GK', 87, '{"club":"Manchester United","nationality":"Netherlands","era":"2000s","categories":[]}'::jsonb),
  ('Hristo Stoichkov', 'FWD', 87, '{"club":"Barcelona","nationality":"Bulgaria","era":"1990s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Javier Zanetti', 'DEF', 87, '{"club":"Inter Milan","nationality":"Argentina","era":"1990s–2000s","categories":[]}'::jsonb),
  ('John Terry', 'DEF', 87, '{"club":"Chelsea","nationality":"England","era":"2000s","categories":[]}'::jsonb),
  ('Marcel Desailly', 'DEF', 87, '{"club":"AC Milan","nationality":"France","era":"1990s–2000s","categories":[]}'::jsonb),
  ('Michael Ballack', 'MID', 87, '{"club":"Bayern Munich","nationality":"Germany","era":"2000s","categories":[]}'::jsonb),
  ('Michael Laudrup', 'MID', 87, '{"club":"Barcelona","nationality":"Denmark","era":"1980s–90s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Nemanja Vidić', 'DEF', 87, '{"club":"Manchester United","nationality":"Serbia","era":"2000s–10s","categories":[]}'::jsonb),
  ('Ashley Cole', 'DEF', 86, '{"club":"Chelsea","nationality":"England","era":"2000s","categories":[]}'::jsonb),
  ('Davor Šuker', 'FWD', 86, '{"club":"Real Madrid","nationality":"Croatia","era":"1990s","categories":[]}'::jsonb),
  ('Fernando Redondo', 'MID', 86, '{"club":"Real Madrid","nationality":"Argentina","era":"1990s–2000s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Filippo Inzaghi', 'FWD', 86, '{"club":"AC Milan","nationality":"Italy","era":"2000s","categories":[]}'::jsonb),
  ('Gaetano Scirea', 'DEF', 86, '{"club":"Juventus","nationality":"Italy","era":"1970s–80s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Gheorghe Hagi', 'MID', 86, '{"club":"Galatasaray","nationality":"Romania","era":"1980s–90s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Ian Rush', 'FWD', 86, '{"club":"Liverpool","nationality":"Wales","era":"1980s–90s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Jimmy Greaves', 'FWD', 86, '{"club":"Tottenham","nationality":"England","era":"1960s–70s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Juan Sebastián Verón', 'MID', 86, '{"club":"Lazio","nationality":"Argentina","era":"1990s–2000s","categories":[]}'::jsonb),
  ('Lilian Thuram', 'DEF', 86, '{"club":"Juventus","nationality":"France","era":"1990s–2000s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Michael Owen', 'FWD', 86, '{"club":"Liverpool","nationality":"England","era":"2000s","categories":[]}'::jsonb),
  ('Pavel Nedvěd', 'MID', 86, '{"club":"Juventus","nationality":"Czech Republic","era":"1990s–2000s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Peter Shilton', 'GK', 86, '{"club":"Nottingham Forest","nationality":"England","era":"1970s–80s","categories":[]}'::jsonb),
  ('Ronald Koeman', 'DEF', 86, '{"club":"Barcelona","nationality":"Netherlands","era":"1980s–90s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Carlos Tévez', 'FWD', 85, '{"club":"Manchester City","nationality":"Argentina","era":"2000s–10s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Claude Makélélé', 'MID', 85, '{"club":"Chelsea","nationality":"France","era":"2000s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Diego Milito', 'FWD', 85, '{"club":"Inter Milan","nationality":"Argentina","era":"2000s–10s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Edgar Davids', 'MID', 85, '{"club":"Juventus","nationality":"Netherlands","era":"1990s–2000s","categories":[]}'::jsonb),
  ('Hernán Crespo', 'FWD', 85, '{"club":"Lazio","nationality":"Argentina","era":"1990s–2000s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Jaap Stam', 'DEF', 85, '{"club":"Manchester United","nationality":"Netherlands","era":"1990s–2000s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Neville Southall', 'GK', 85, '{"club":"Everton","nationality":"Wales","era":"1980s–90s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Ricardo Carvalho', 'DEF', 85, '{"club":"Chelsea","nationality":"Portugal","era":"2000s–10s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Robbie Fowler', 'FWD', 85, '{"club":"Liverpool","nationality":"England","era":"1990s–2000s","categories":[]}'::jsonb),
  ('Yaya Touré', 'MID', 85, '{"club":"Manchester City","nationality":"Ivory Coast","era":"2000s–10s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Aldair', 'DEF', 84, '{"club":"Roma","nationality":"Brazil","era":"1990s–2000s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Antonio Di Natale', 'FWD', 84, '{"club":"Udinese","nationality":"Italy","era":"2000s–10s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('César Azpilicueta', 'DEF', 84, '{"club":"Chelsea","nationality":"Spain","era":"2010s–20s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Esteban Cambiasso', 'MID', 84, '{"club":"Inter Milan","nationality":"Argentina","era":"2000s–10s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Fernandinho', 'MID', 84, '{"club":"Manchester City","nationality":"Brazil","era":"2010s–20s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Júlio César', 'GK', 84, '{"club":"Inter Milan","nationality":"Brazil","era":"2000s–10s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Keylor Navas', 'GK', 84, '{"club":"Real Madrid","nationality":"Costa Rica","era":"2010s–20s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Michael Carrick', 'MID', 84, '{"club":"Manchester United","nationality":"England","era":"2000s–10s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Roberto Firmino', 'FWD', 84, '{"club":"Liverpool","nationality":"Brazil","era":"2010s–20s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Santi Cazorla', 'MID', 84, '{"club":"Arsenal","nationality":"Spain","era":"2010s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Sepp Maier', 'GK', 84, '{"club":"Bayern Munich","nationality":"Germany","era":"1970s–80s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Youri Djorkaeff', 'MID', 84, '{"club":"Inter Milan","nationality":"France","era":"1990s–2000s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Demetrio Albertini', 'MID', 83, '{"club":"AC Milan","nationality":"Italy","era":"1990s–2000s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Edin Džeko', 'FWD', 83, '{"club":"Roma","nationality":"Bosnia","era":"2010s–20s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Gary Pallister', 'DEF', 83, '{"club":"Manchester United","nationality":"England","era":"1990s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Olivier Giroud', 'FWD', 83, '{"club":"Arsenal","nationality":"France","era":"2010s–20s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Ricardo Quaresma', 'FWD', 83, '{"club":"Porto","nationality":"Portugal","era":"2000s–10s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Samir Handanović', 'GK', 83, '{"club":"Inter Milan","nationality":"Slovenia","era":"2010s–20s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Tomáš Rosický', 'MID', 83, '{"club":"Arsenal","nationality":"Czech Republic","era":"2000s–10s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Georgi Kinkladze', 'MID', 82, '{"club":"Manchester City","nationality":"Georgia","era":"1990s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Joël Matip', 'DEF', 82, '{"club":"Liverpool","nationality":"Cameroon","era":"2010s–20s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Mark van Bommel', 'MID', 82, '{"club":"Bayern Munich","nationality":"Netherlands","era":"2000s–10s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Pedro Rodríguez', 'FWD', 82, '{"club":"Barcelona","nationality":"Spain","era":"2010s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Wissam Ben Yedder', 'FWD', 82, '{"club":"Monaco","nationality":"France","era":"2010s–20s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Bacary Sagna', 'DEF', 81, '{"club":"Arsenal","nationality":"France","era":"2000s–10s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Dirk Kuyt', 'MID', 81, '{"club":"Liverpool","nationality":"Netherlands","era":"2000s–10s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Joe Hart', 'GK', 81, '{"club":"Manchester City","nationality":"England","era":"2010s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('John Arne Riise', 'DEF', 81, '{"club":"Liverpool","nationality":"Norway","era":"2000s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Jonny Evans', 'DEF', 81, '{"club":"Manchester United","nationality":"Northern Ireland","era":"2010s–20s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Phil Jagielka', 'DEF', 81, '{"club":"Everton","nationality":"England","era":"2000s–10s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Tim Howard', 'GK', 81, '{"club":"Everton","nationality":"USA","era":"2000s–10s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Jussi Jääskeläinen', 'GK', 80, '{"club":"Bolton Wanderers","nationality":"Finland","era":"2000s–10s","categories":["UNDERRATED_XI"]}'::jsonb),
  ('Peter Crouch', 'FWD', 80, '{"club":"Stoke City","nationality":"England","era":"2000s–10s","categories":["UNDERRATED_XI"]}'::jsonb);
